### ISSUE TITLE
Convert Eclipse project to Maven project

### ISSUE THREAD

**Issue by Erik142** [Erik142/PasswordManager#22]
Since the PasswordDatabase implementation uses the SQLite library, maybe it would be nice to convert our project to a Maven project so that we can add the SQLite jar as a dependency to the project which will automatically be downloaded to the system if necessary?

Converting the project to a Maven project can be done from within Eclipse, and Eclipse supports Maven projects. From there it should be pretty straightforward to add the jar as a dependency since it exists in the Maven central repository

https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc

@ErminFazlic pinging you here, let me know what you think.

Link to Apache Maven homepage: https://maven.apache.org/

This will make it easier to build the software and possibly add more jars for dependencies in the future (Maybe some custom elements for the View for example? @Arian421)!

If anyone feel like doing this, please assign this issue to yourself before starting to work on it 😄

**Comment by Erik142** [comment]
I created a test branch where our project is converted into a maven one. It seems to work well for me at least. SQLite is automatically added as a project dependency, so no need to add the jar manually! This could also be used for cool stuff like adding unit tests to our project and have them automatically execute in Github when we merge code into the master branch or create a pull request. Very flexible solution imo!

[maven-project](/Erik142/PasswordManager/tree/dev/maven-project)

**Comment by ErminFazlic** [comment]
It looks like a smart solution, I say go for it!
